name: Publish

on:
  workflow_dispatch:
  push:
    tags:
      - "v*"

jobs:
  publish:
    name: build and publish docker image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: docker/login-action@v3.6.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Extract version from version.go
        id: version
        run: |
          VERSION=$(grep 'Version =' version.go | awk '{print $3}' | tr -d '"')
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "version=$VERSION" >> $GITHUB_OUTPUT
      - name: Check tag matches version.go
        run: |
          TAG_VERSION=${GITHUB_REF#refs/tags/}
          VERSION=${{ steps.version.outputs.version }}
          echo "Tag version: $TAG_VERSION"
          echo "Version.go: $VERSION"
          if [ "$TAG_VERSION" != "$VERSION" ]; then
            echo "Error: Git tag ($TAG_VERSION) does not match version.go ($VERSION)"
            exit 1
          fi
      - name: Extract metadata for release
        id: meta
        uses: docker/metadata-action@v5.8.0
        with:
          images: my-docker-hub-namespace/my-docker-hub-repository
          tags: |
            type=raw,value=${{ steps.version.outputs.version }}
      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@v6.18.0
        with:
          context: .
          file: ./Dockerfile
          push: true
          labels: ${{ steps.meta.outputs.labels }}
          tags: ${{ steps.meta.outputs.tags }}
          platforms: linux/amd64
      - name: Generate artifact attestation
        uses: actions/attest-build-provenance@v3
        with:
          subject-name: index.docker.io/my-docker-hub-namespace/my-docker-hub-repository
          subject-digest: ${{ steps.push.outputs.digest }}
          push-to-registry: true
